### ISSUE TITLE
Unable to run script

### ISSUE THREAD

**Issue by ghost** [rementis/Plex_Scripts#1]
When I try to run the script on my Ubuntu server
`perl find_non_h264.pl`

I get an error
> syntax error at find_non_h264.pl line 10, near "<"
> Excessively long <> operator at find_non_h264.pl line 21.

**Comment by rementis** [comment]
Make sure it was copied/pasted properly or downloaded correctly.

Did you change the $directory variable?


Apr 22, 2020 9:31:20 PM cuzimabot <notifications@github.com>:

**Comment by rementis** [comment]
Also you might want to try https://github.com/rementis/Plex_Scripts/blob/master/find_codecs.pl

**Comment by ghost** [comment]
Ah I used wget which had downloaded the 'page' instead of the actual file. It's working now. Thanks!!
